name: Versioning Package

on:
  push:
    branches: [ main ]

jobs:
  build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
      - name: Initialize Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8   
      - name: Get latest tag
        id: latest_tag
        run: |
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
      - name: Get current date
        id: current_date
        run: |
          echo "::set-output name=date::$(date +%Y.%m.%d)"
      - name: Increment patch number
        id: increment_patch
        run: |
          patch=$(echo "${{ steps.latest_tag.outputs.tag }}" | cut -d '.' -f 4)
          patch=$((patch+1))
          echo "::set-output name=patch::${patch}"
      - name: Set new tag
        id: new_tag
        run: |
          new_tag="${{ steps.current_date.outputs.date }}.${{ steps.increment_patch.outputs.patch }}"
          echo "::set-output name=tag::${new_tag}"
          git tag "${new_tag}"
      - name: Set version in setup.py
        run: |
          sed -i "s/version='.*'/version='${{ steps.new_tag.outputs.tag }}'/g" setup.py
      - name: Build binary wheel and a source tarball
        run: python setup.py sdist
      - name: Push new tag
        run: git push origin "${{ steps.new_tag.outputs.tag }}"
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
